In [9]:
"""
    Notebook for streaming data from a microphone in realtime

    audio is captured using pyaudio
    then converted from binary data to ints using struct
    then displayed using matplotlib

    scipy.fftpack computes the FFT

    if you don't have pyaudio, then run

    >>> pip install pyaudio

    note: with 2048 samples per chunk, I'm getting 20FPS
    when also running the spectrum, its about 15FPS
"""
import matplotlib.pyplot as plt
import numpy as np
import pyaudio
import struct
from scipy.fftpack import fft
import sys
import time


class AudioStream(object):
    def __init__(self):

        # stream constants
        self.CHUNK = 1024 * 2
        self.FORMAT = pyaudio.paInt16
        self.CHANNELS = 1
        self.RATE = 44100
        self.pause = False

        # stream object
        self.p = pyaudio.PyAudio()
        self.stream = self.p.open(
            format=self.FORMAT,
            channels=self.CHANNELS,
            rate=self.RATE,
            input=True,
            output=True,
            frames_per_buffer=self.CHUNK,
        )
        self.start_plot()

    def start_plot(self):

        print('stream started')
        frame_count = 0
        start_time = time.time()

        while not self.pause:
            data = self.stream.read(self.CHUNK)
            data_int = struct.unpack(str(2 * self.CHUNK) + 'B', data)
            data_np = np.array(data_int, dtype='b')[::2] + 128
            yf = fft(data_int)
            yfft = np.abs(yf[0:CHUNK] * 2 / (256 * CHUNK))

        else:
            self.fr = frame_count / (time.time() - start_time)
            print('average frame rate = {:.0f} FPS'.format(self.fr))
            self.exit_app()

    def exit_app(self):
        print('stream closed')
        self.p.close(self.stream)

    def onClick(self, event):
        self.pause = True


if __name__ == '__main__':
    AudioStream()

stream started
[0.01401138 0.01383991 0.01333306 ... 0.01103246 0.01159938 0.01194817]
[1.76229858 0.55810806 0.1339674  ... 0.11507345 0.07418993 0.00940218]
[1.97266006 0.03610036 0.62571289 ... 0.02424849 0.6085414  0.10856737]
[1.78586578 0.34478986 0.60303015 ... 0.08730142 0.36599447 0.20080615]
[1.59365845 0.50027775 0.71474652 ... 0.12447129 0.14825846 0.07029541]
[2.28825378 0.25446828 0.46374947 ... 0.03070397 0.03824701 0.03013395]
[1.89263535 0.20453424 0.46865076 ... 0.03898    0.02031116 0.01058411]
[1.96048355 0.1492962  0.54350922 ... 0.1269169  0.12449267 0.03290577]
[1.82795715 0.37470624 0.90248129 ... 0.03069227 0.03533066 0.02427293]
[1.88695908 0.59736343 0.43135616 ... 0.00287562 0.01544321 0.01278671]
[1.97104645 0.04472384 0.63812302 ... 0.02827708 0.04102815 0.01058857]
[2.10290527 0.46825237 0.99262928 ... 0.00923664 0.03590835 0.01193649]
[1.67808533 0.25133722 0.51542576 ... 0.0465     0.03342738 0.00354359]
[1.76417542 0.2602949  0.66587392 ... 0.02215194 

KeyboardInterrupt: 